name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  build-linux-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: samp-gps-linux-release
          path: GPS.so
